apiVersion: apps/v1
kind: Deployment
metadata:
  # Name of the deployment resource, used to identify and manage it
  name: swear-stop-api
  labels:
    # Label categorizing the application as part of the backend
    tier: backend
    # Layer tag to help manage different application components (e.g., backend, backend)
    layer: api
spec:
  # Number of pod replicas (only 1 instance for now)
  replicas: 1
  selector:
    # Selector to match the pods created by this deployment based on labels
    matchLabels:
      tier: backend
      layer: api
  template:
    metadata:
      labels:
        # Labels to associate with the pod created by this deployment
        tier: backend
        layer: api
    spec:
      imagePullSecrets:
        - name: swear-stop-docker-registry
      containers:
        - name: swear-stop-api
          # Docker image for the main backend application
          image: danukawaidyatillake/text-moderator-api-app:v0.0.66
          # Exposing port 80 for web traffic
          ports:
            - containerPort: 80
          env:
            # Setting the FPM host environment variable to communicate with the backend
            - name: FPM_HOST
              value: localhost:9000
          # Additional environment variables pulled from ConfigMap and Secret
          envFrom:
            - configMapRef:
                name: swear-stop-api-config
            - secretRef:
                name: swear-stop-api-secret
